markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Joosep Pata
url: jpata.github.io
description: A fantastic blog that is fantastic.
twitter: JoosepPata
